### ISSUE TITLE
Autoloader?

### ISSUE THREAD

**Issue by oucil** [PhpUnitsOfMeasure/php-units-of-measure#32]
First, great work on the library, looking forward to putting it to use!

Next, maybe I'm missing it, but where is the autoloader for this library?  None of the examples refer to one, and there are many `use` statements throughout, but no corresponding `include` or `require` statements so without a lot of work manually loading all the dependencies, every call fails....without fail.

P.S. We're not using composer.

**Comment by ecommunities** [comment]
Appreciate the detailed response and the pointer to the PSR-4 materials.  Ours is a very large project with its own autoloader and corresponding folder/class framework, and we use a number of custom loaders provided with other utilities like this one for those of us not using Composer or wanting to minimize reliance on third party software (I know, ironic) outside of small utility classes like this one.  

I appreciate that we can fall back on the standard, but I might point out that, sadly, there are many more people not adhering to standards than there are to them for a variety of reasons, and that in choosing to explicitly not include an autoloader, you're making it more difficult for the majority of us to integrate your code.  Many people, us included, are pigeon holed by established projects that didn't have the benefit of the standard at the time the were created, and/or don't have the flexibility to refactor at this point.

Don't get me wrong, I really appreciate your offering this class and maintaining it, but I would argue that an autoloader is indeed very much in-scope and encourage you to supply one with your utility in the future.  Given time, and of coarse your interest, I may be able to find time to send you a PR, but won't bother if you're not interested.

Again, thanks for your efforts and for sharing!

Cheers!
