### ISSUE TITLE
Add KPH and MPH to Velocity

### ISSUE THREAD

**Issue by four43** [PhpUnitsOfMeasure/php-units-of-measure#34]
Curious if you need help with this, I can create a pull request if there is interest.

Thanks,
-Seth

**Comment by four43** [comment]
I see you have a lot of ways to extend this, which is great. KPH and MPH just seemed common enough it would be nice to provide them out of the box and tested. As a developer I know I'm not relying on testing my callables then. 

Thanks,
-Seth

**Comment by triplepoint** [comment]
If you'd like to submit a PR that'd be great; those are entirely reasonable units to add.

It's worth noting that I'm working on a new feature that allows derived quantities (like velocity, area, volume, acceleration, mass density, etc) to be defined by referencing the already-defined base quantities (length, mass, time, etc).  This will have the nice effect of getting any combination of the associated units for free (for example megameters / year for velocity).

But I have no ETA on that work, so for now if you'd like to add these units with the current defining strategy and submit a PR, that would be fine.

**Comment by martinlindhe** [comment]
This is included in #40

**Comment by triplepoint** [comment]
Agreed.
