### ISSUE TITLE
Velocity vs. Speed

### ISSUE THREAD

**Issue by martinlindhe** [PhpUnitsOfMeasure/php-units-of-measure#39]
Hello. I am working on a little patch for this code, and in it i am extending the "Velocity" class with additional units.

Since it currently only has one unit ("meters per second"), i am guessing noone is actually using it. So might it be possible if we rename it to "Speed" instead?

If ok, I will rename the class to Speed in my branch before sending a pull request

From wikipedia: 
"Distinction between speed and velocity Speed describes only how fast an object is moving, whereas velocity gives both how fast and in what direction the object is moving. If a car is said to travel at 60 km/h, its speed has been specified."

**Comment by martinlindhe** [comment]
Here is my proposed change:

https://github.com/martinlindhe/php-units-of-measure/commit/263428103d52723af2052ba62912d7279ee99617

**Comment by triplepoint** [comment]
I believe this was addressed as part of #40.  I  agreed that in hindsight, speed might've been more technically accurate, but changing the name now would be a backwards-incompatible breakage and the ambiguity is unlikely to cause confusion as it stands.
