### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by alwinkpc** [PhpUnitsOfMeasure/php-units-of-measure#42]
Greetings,

A fix:

Since version 1.2.0 you have composer.json to use PHP >= 5.3.5. In that version you use array in short notation with bracket wich is not available since 5.4

Also, In version 1.3.3 you downgrade to PHP >= 5.3.0 wich is even worse due to in that version you use traits (also 5.4 feature)

I'm new to github, so I hope to be writing in the right place

**Comment by triplepoint** [comment]
Hello,
  You're right, this is definitely busted.

  Regarding the short-array syntax, that's a complete mistake on my part.  I should've had php 5.3 in the travis build matrix, and that would've revealed the incompatibility.  Same goes for using traits.  It's obvious the requirement for this library should've always been php >=5.4.0.  I've been using php 5.4+ for ages, and I'm afraid I just never noticed that this library wasn't 5.3 compatible.

  I don't think stepping back to php >=5.3.0 in 1.3.3 was worse than what 1.3.1 was doing, but its certainly no better.  For the record, that downgrade in version was motivated by this ticket https://github.com/triplepoint/php-units-of-measure/issues/38.

  In any case, I would encourage anyone using this library to use the latest (currently 2.0.0) version.  I'm afraid I don't have the time to maintain multiple versions of the library in perpetuity.  I may issue a minor patch to the 1.3.x line to add the php 5.3 travis requirement to the build, just to highlight the failure, but I don't see myself revising the 1.x line to be fully php 5.3 compatible.

 Thanks for bringing this up though, it definitely highlights an area of support to which I need to pay more attention.

**Comment by alwinkpc** [comment]
No problem. I've been more open-minded to start using third party components on my systems lately, so I will review your code when I have the time. If I understand this (github, collaborating, ..) right I probably could fork the 1.3.x version and pull-request you the updates

**Comment by triplepoint** [comment]
A fork and pull request would be complicated by the fact that I don't maintain separate branches for the 1.x and 2.x versions.  Since it looks like there's at least some interest in continuing to make improvements to the 1.x line, I guess it makes sense for me to set that up sooner than later.  I'll look into it when I get some time.

On a larger note, if you have any questions about 3rd-party collaboration on github in general, feel free to drop me an email, and I'll do my best to share what I've seen so far.

**Comment by anedisi** [comment]
yeah, it looks like the last version compatible with 5.3 is 1.1.2

**Comment by triplepoint** [comment]
I'm afraid I let this go too long and never addressed the original issue.

At this point, I'm not likely to address php 5.3 compatibility, given it's out-of-support status.
