### ISSUE TITLE
Is it possible to get all supported units?

### ISSUE THREAD

**Issue by rajivseelam** [PhpUnitsOfMeasure/php-units-of-measure#46]
For example, if I want to give a drop down in user interface where UOM is chosen by user, I have to manually add list of units supported. Is it possible via some API with library? getSupportedUnits()?

**Comment by anjalirana** [comment]
Any update on this?

**Comment by triplepoint** [comment]
The referenced commit to soyuka's branch looks reasonable.  I'd probably accept that as it stands if a pull request was submitted.  Otherwise, we'll get around to implementing something similar.

**Comment by soyuka** [comment]
Added a Pull request (+test)

**Comment by triplepoint** [comment]
The associated PR #46 for this got merged, thanks for the contribution.
