### ISSUE TITLE
php-units-of-measure should replace triplepoint

### ISSUE THREAD

**Issue by aaronb-cg** [PhpUnitsOfMeasure/php-units-of-measure#49]
Hi. We were using `triplepoint/php-units-of-measure` which we're told is now deprecated so we switched to `php-units-of-measure/php-units-of-measure`. The problem is that the latter doesn't have a ['replace'](https://getcomposer.org/doc/04-schema.md#replace) directive for the former. As it stands when we pull in the latter it does so but it does not remove the former so we ended up with both and then the autoload building failed as there's two versions of each class.

Here's how I'd expect it to look in your composer.json:
```javascript
"replace": {
    "triplepoint/php-units-of-measure": "*"
}
```

We've worked around this by manually calling `composer remove triplepoint/php-units-of-measure`.
\[edit\] Typo.

**Comment by triplepoint** [comment]
Hi, thanks for the input; I didn't know that was a feature of Composer.

I added that attribute in composer.json in develop.  It's probably about time for a bugfix release anyway, so that should be showing up soon in a new tag.

Thanks again for the feedback.

**Comment by triplepoint** [comment]
New release 2.0.1 is out in packagist, it should have the changes to the composer.json you mentioned.

**Comment by aaronb-cg** [comment]
Great, thanks.
