### ISSUE TITLE
Add support for Power

### ISSUE THREAD

**Issue by pierpaolocira** [PhpUnitsOfMeasure/php-units-of-measure#67]
Do you think it is possible to add the support for "Power" (in Watts, plus SI prefixes))?
If you are interested I can open a pull request...
Thank you

**Comment by triplepoint** [comment]
closing, merged #69

**Comment by khalwat** [comment]
It looks like a release was never tagged to include this change, so `composer install` doesn't pull down the latest source if we have a reasonable semver like `^2.1.0`. The last tagged version was `2.1.0` from July 2016:

https://github.com/PhpUnitsOfMeasure/php-units-of-measure/releases
