### ISSUE TITLE
Does this project uses the UCUM system?

### ISSUE THREAD

**Issue by ppazos** [PhpUnitsOfMeasure/php-units-of-measure#88]
https://ucum.org/

**Comment by triplepoint** [comment]
It does not; I'd never heard of it before today.

**Comment by ppazos** [comment]
thanks @triplepoint UCUM is an international standard for a units of measure system that allows to convert between multipliers and dividers of the same unit (g => Kg), and between units (°C => °F). Since the name was the same as this project, I thought this might be an implementation of the UCUM (Unified Code for Units of Measure) system in PHP.
